{application,project3,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"project3"},
              {modules,['Elixir.NodeCreator','Elixir.Project3Application',
                        'Elixir.Register','Elixir.RoutingTable',
                        'Elixir.Simulator','Elixir.Tapestry.Node']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Project3Application',[]}}]}.
